### ISSUE TITLE
CSS/JS watchers in forked static site version

### ISSUE THREAD

**Issue by peterankelein** [Alecaddd/gulp-es6#1]
Hi Alessandro,

I've forked this and refactored things for more of a static site usage (https://github.com/peterankelein/gulp-es6) where I have a `src` and `dist` folder. For the most part it all works (task pipes work, files are copied properly to the dist folder, style and js paths are correct when opening the html in the `dist` folder. However, I'm running into an issue where the CSS and JS aren't loading during the watch....I'm actually getting mime type errors for both in console so they won't load. I'm assuming there is some path issue I'm missing in the gulpfile or some extra step but I haven't been able to suss it out. 

Note that I'm putting HTML into src and have changed the browserSync base to `/src/` in order to load the page. I could get the CSS and JS to load prior by having the html in the root directory and leaving the base to `./` but it's not very clean. I know you've moved on to webpack but if you have a second, could you load up my repo and see if you can spot anything off the bat that I need to change?

Thx,
Pete

**Comment by Alecaddd** [comment]
Hi, thanks for using my code, I'm glad is helpful to you.
I'm gonna close this issue as it's not related to this code base.
Could you recreate this issue in your repo and add me as a collaborator? I'll take a look

**Comment by peterankelein** [comment]
No problem. Issue re-created and Invite sent.
